include: package:austerity/analysis_options.yaml

analyzer:
  errors:
    public_member_api_docs: ignore
    prefer_expression_function_bodies: ignore
    always_put_required_named_parameters_first: ignore