name: pick_and_eat_app
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # i18n
  flutter_localizations:
    sdk: flutter
  intl: 0.18.0

  # Routing
  auto_route: 7.8.0 

  # State management
  mobx: 2.2.0
  flutter_mobx: 2.0.6+5

  # Models
  freezed_annotation: 2.4.1

  # Misc
  meta: 1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # MVC
  mobx_codegen: 2.3.0

  # Code quality
  flutter_lints: 2.0.2

  # Models
  freezed: 2.4.1

  # Routing
  auto_route_generator: 7.3.1                  

  # Code generation
  build_runner: 2.4.6

flutter:
  uses-material-design: true
  generate: true
